apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kubeapps.84-235-173-41.nip.io
  rules:
  - host: kubeapps.84-235-173-41.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubeapps
            port:
              number: 80
